spring:
  redis:
    host: ${REDIS_HOST:10.0.4.134}
    port: ${REDIS_PORT:8086}
    lettuce:
      pool:
        max-active: 300

feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true

ribbon:
  eureka:
    enabled: true # 开启eureka轮询
  eager-load:
    enabled: true  # 开启Ribbon的饥饿加载模式(防止第一次请求超时的问题)
    clients: user, product # 指定需要开启的服务(需要开启Ribbon的饥饿加载模式)
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

# 设置最大容错超时时间
# 执行超时时间为9秒，会对服务熔断路由defaultfallback生效
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 90000

# 设置最大容错超时时间
hystrix:
  threadpool:
    default:
      coreSize: 100
      maximumSize: 5000
      allowMaximumSizeToDivergeFromCoreSize: true
      maxQueueSize: -1
  command:
    default:
      circuitBreaker:
        # 是否强制将断路器设置成开启状态（true开启，false不开启）最好不开启否者会导致访问服务一直熔断
        foreOpen: false
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 900000

jetcache:
  statIntervalMinutes: 15  # 统一间隔
  areaInCacheName: false  # 设置不把areaName作为Key前缀
  hidePackages: com.runyuanj # 如果@Cached和@CreateCache的name是自动生成的，会默认的将包名和方法名作为前缀,该设置会被从包名中截掉
  local:
    # 默认永久本地缓存
    default:
      type: caffeine
      keyConvertor: fastjson
  remote:
    # 默认永久的远程缓存
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      expireAfterWriteInMillis: 1000 # 以毫秒为单位指定超时时间的全局配置
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${spring.redis.host}
      port: ${spring.redis.port}
      # password: ${REDIS_PASSWORD:root}