spring:
  redis:
    host: ${REDIS_HOST:10.0.4.138}
    port: ${REDIS_PORT:8086}
    lettuce:
      pool:
        max-active: 300
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:111.229.218.230}:${DATASOURCE_PORT:3306}/sc_auth?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:dontcrack123}
  ribbon:
    ConnectTimeout: 3000
    ReadTimeout: 3000


  cloud:
    stream:
      instanceCount: 2
      instanceIndex: 1
      autoRebalanceEnabled: true
